### ISSUE TITLE
Setting icon

### ISSUE THREAD

**Issue by jaubourg** [pavel-a/ddverpatch#1]
First of all thank you for this tool, it works like a charm.

I'm trying to change the icon of an exe and I noticed verpatch does not support this. Sadly, I tried multiple command-line tools for this and they plain not work because they're old or they break the exe (I suspect the checksum is not properly re-computed if at all).

I was wondering if you would be open to add the option to verpatch.

As a side-note, pre-built versions on github would be awesome too. I had to chase for one to avoid manual compilation.

Thanks again for your work.

**Comment by pavel-a** [comment]
Pre-built binary is available in Releases.  (maybe it can be reworked into a new github "package"...)
Icons can be added with the existing option to add a resource, /rf.

Thanks,
P.
