### ISSUE TITLE
"err opening file for rechecksum"

### ISSUE THREAD

**Issue by scimax** [pavel-a/ddverpatch#3]
We were using verpatch now for a while without problems, but now it throws an error which we don't understand. When calling verpatch it outputs:
```sh
err GetShortPathName, gle=2
err opening file for rechecksum (unicode path)
err open file for reading extra data 2
Failed to read extra data
```

Is it an error in verpatch or might something be wrong with the command line arguments?
```
./verpatch.exe " dist/App Name/App Name.exe" 0.7.0.1 -va -pv 0.7.0.1 -s ProductName "App Name" -s copyright "(c) 2018 Our Names" -s company "Our Company Name & something"
```
I changed the arguments to make it anonymous, but left in the important Non-ASCII characters.

**Comment by pavel-a** [comment]
Usually this mean that the source exe file cannot be opened for read & write. Try to understand why.
